image: composer:latest

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
  - vendor/

stages:
  - test
  - tag

testing:
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: test
  script:
  # run tests
  - echo "Running PHPUnit Tests"
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  - ./vendor/bin/pint

tag_release:
  stage: tag
  only:
    - master
  script:
    - VERSION="$(php -r "echo json_decode(file_get_contents('./composer.json'), true)['version'];")";
    - MESSAGE="$(php -r "echo json_encode(['name' => 'Version $VERSION', 'tag_name' => '$VERSION', 'description' => file_get_contents('./changelog/$VERSION.md')]);")";
    - git config --global user.email "informatica@altracorporacion.es"
    - git config --global user.name "informatica_altra"
    - git remote add api-origin https://oauth2:${OAUTH2_TOKEN}@gitlab.com/informatica_altra/altra-dto
    - >
      if [ $(git tag -l "$VERSION") ]; then
        echo "Version $VERSION already exists"
      else
        git tag -a $VERSION -m "Version $VERSION"
        git push api-origin $VERSION
        curl --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $OAUTH2_TOKEN" \
           --data "$MESSAGE" \
           --request POST https://gitlab.com/api/v4/projects/informatica_altra/altra-dto/releases
      fi


